# Keep in sync with mail_server_hostname in mailserver role
webmail_subdomain: "mail"
webmail_domain: "{{ webmail_subdomain }}.{{ domain }}"
webmail_language: "en_US"

secret_root: '{{ inventory_dir | realpath }}'
secret_name: 'secret'
secret: '{{ secret_root + "/" + secret_name }}'
