---
# Defines tasks applicable for postgreSQL

- name: Install Postgres
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - postgresql
    - python-psycopg2
  tags:
    - dependencies

- name: Set password for PostgreSQL admin user
  become: true
  become_user: postgres
  postgresql_user: name={{ db_admin_username }} password={{ db_admin_password }} encrypted=yes
